model:
  base_model: "asafaya/bert-base-arabic"
  hidden_size: 768
  num_hidden_layers: 12
  num_attention_heads: 12
  intermediate_size: 3072
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 512
  vocab_size: 64000
  
cultural:
  lambda_cultural: 0.7
  enhancement_threshold: 0.5
  pattern_weight: 0.6
  element_weight: 0.4

generation:
  max_length: 512
  num_beams: 5
  temperature: 0.7
  no_repeat_ngram_size: 3
  do_sample: true
  early_stopping: true
